collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.7365592
color:
  saturation: 0.7329749
  brandStrength: 0.2508961
  lightness: 0.6612903
  brandColors:
    - '#08090D'
    - '#FFFADD'
    - '#FC7726'
    - '#A0442D'
    - '#49686A'
  rhythmicContrast: 0.4946237
layout_spectrum: 0.2598566
name: GospelFuel
