collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.7365592
color:
  saturation: 0.7329749
  brandStrength: 0.7526882
  lightness: 0.8333333
  brandColors:
    - '#3B372C'
    - '#6F251C'
    - '#B83F22'
    - '#DF3F25'
    - '#3D1C15'
  rhythmicContrast: 1
layout_spectrum: 0.3548387
name: GospelFuel
