collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8100358
color:
  saturation: 1
  brandStrength: 0.7634408
  lightness: 0.688172
  brandColors:
    - '#FEFEFE'
    - '#515151'
    - '#010101'
    - '#DD5E30'
    - '#E80C10'
  rhythmicContrast: 1
layout_spectrum: 0.3172043
name: GospelFuel
