collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5215054
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#FEFEFE'
    - '#515151'
    - '#010101'
    - '#DD5E30'
    - '#E80C10'
  lightness: 0.688172
typography_spectrum: 0.8100358
layout_spectrum: 0
name: GospelFuel
