collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0.5286738
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#C6792C'
    - '#F5BE3B'
    - '#4D1C1A'
    - '#71BADA'
  rhythmicContrast: 0
typography_spectrum: 0.3243728
layout_spectrum: 0.2706093
name: GospelFuel
