collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7329749
  brandStrength: 0.7526882
  lightness: 0.8333333
  brandColors:
    - '#08090D'
    - '#FFFADD'
    - '#FC7726'
    - '#A0442D'
    - '#49686A'
  rhythmicContrast: 1
typography_spectrum: 0.7365592
layout_spectrum: 0.3548387
name: GospelFuel
